# Fix colors inside tmux
set -g default-command "${SHELL}"
set -g default-terminal "st-256color"
set -as terminal-features ",st-256color:RGB"

# Unbind annoying defaults and make splits intuitive
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Minimalist status bar (Gruvbox matching, no distraction)
set -g status-style bg='#282828',fg='#ebdbb2'
set -g status-left ' [#S] '
set -g status-right ' %Y-%m-%d %H:%M '
set -g window-status-current-style bg='#458588',fg='#282828',bold
